### ISSUE TITLE
Handle handshake packet

### ISSUE THREAD

**Issue by xPaw** [benjojo/mcod#1]
http://wiki.vg/Protocol#Handshake

You won't need to start the server, unless it's actually a login handshake, and reply with motd banner data when needed.

**Comment by benjojo** [comment]
Done :tada:

**Comment by benjojo** [comment]
![screenshot from 2015-02-02 23 13 22](https://cloud.githubusercontent.com/assets/1504626/6011203/23610702-ab31-11e4-97a8-6162f2052c81.png)

Here is what it looks like in action, Note the backend is down, but the banner at the top still lives

**Comment by xPaw** [comment]
Your current implementation is quite buggy. Most of the time it just shows 'Pinging...' in Minecraft, and I think it somehow caches login response, instead of banner response. It's also possible to trigger 'new player joining' by just refreshing the server list. And when you try join the server, it says 'Serving the banner from cache' instead.

**Comment by benjojo** [comment]
Can you try and record a video to reproduce (show the back end port and the one covered by mcod + the output) so I can look into this?

I did try and ensure that this would not munch anything up but I might be wrong
